MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
<<<<<<< HEAD
  PRETRAIN_CKPT: "/root/autodl-tmp/wsp_uusic/blsamus/pretrained_ckpt/swin_tiny_patch4_window7_224.pth"
=======
  PRETRAIN_CKPT: "/root/autodl-tmp/wsp_uusic/blsamus/pretrained_ckpt/swin_tiny_patch4_window7_224.pth"
>>>>>>> 8f14ae534c91fbc05719c7ba34bcb7cc1b607768
  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 96
    ENCODER_DEPTHS: [ 4, 4, 4, 4]
    DECODER_DEPTHS: [ 2, 2, 2, 2]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7